apiVersion: v1
kind: Service
metadata:
  namespace: device-service
  labels:
    app: device-service
  name: device-service
spec:
  ports:
  
    - protocol: TCP
      port: 4444
      targetPort: 4444
   
   
    - protocol: TCP
      port: 34400
      targetPort: 34400
   
  selector:
    app: device-service
  type: ClusterIP
