apiVersion: v1
kind: Service
metadata:
  namespace: tenant-service
  labels:
    app: tenant-service
  name: tenant-service
spec:
  ports:
  
    - protocol: TCP
      port: 8080
      targetPort: 8080
   
   
  selector:
    app: tenant-service
  type: ClusterIP
